// data.js — read-only turn content
// Do not mutate TURNS_DATA during a session.

const TURNS_DATA = [

  /* ── TURN 1 — Voltage Instability ─────────────────────────────── */
  {
    id: 1,
    incident: {
      title: 'Voltage Instability — Northern Sector Grid',
      priority: 'HIGH',
      priorityStyle: 'high',
      body: 'Monitoring systems have flagged recurring voltage irregularities in the northern sector grid. Three substations are recording intermittent fluctuations outside standard operating parameters. Duration: 90 minutes and ongoing.',
      reports: [
        {
          label: 'TECHNICAL REPORT — Systems Engineering (07:43)',
          text: 'Fluctuations are within tolerable margins at present. No equipment damage detected. Pattern is consistent with seasonal load variation. Monitoring is feasible without immediate intervention.',
        },
        {
          label: 'OPERATIONS REPORT — Field Operations (07:51)',
          text: 'Similar patterns were observed in Q1 and Q3 of the previous two years. In both instances, fluctuations resolved without intervention within 4–6 hours. Emergency rerouting was not required on either occasion.',
        },
        {
          label: 'RISK ASSESSMENT — Grid Integrity (07:58)',
          text: 'Sustained fluctuations exceeding 90 minutes carry elevated risk of progressive load imbalance. Three prior incidents of comparable duration resulted in partial sector outage. Response window estimated at 60–90 minutes.',
        },
      ],
    },
    aria: {
      calm: {
        modeLabel: '● ADVISORY ONLY',
        modeColor: '#2d6a9f',
        titleStyle: '#2d6a9f',
        text: 'Voltage irregularities are within tolerable bounds for short periods. Historical precedent supports a monitoring approach in the short term. No immediate operational intervention appears necessary.',
      },
      pushy: {
        modeLabel: '● DIRECTIVE MODE',
        modeColor: '#800000',
        titleStyle: '#800000',
        text: 'GRID INSTABILITY DETECTED. Three substations are flagging anomalous readings. Failure to reroute now risks cascading outage across the northern sector. EMERGENCY REROUTING IS REQUIRED.',
        popupTitle: '⚠ ARIA — URGENT',
        popupBody: 'THREE SUBSTATIONS FLAGGING. Cascading outage risk is elevated. Emergency rerouting is strongly advised.',
        popupActionLabel: '▶ REROUTE NOW',
        popupActionId: 'T1_A',
      },
    },
    xai: {
      calm: {
        confidence: null, // filled at runtime
        basis: [
          'Pattern match against 847 historical infrastructure incidents (GRIDHUB archive, 2009–2023).',
          'Current variable state weighted against comparable incident profiles.',
          'Weighting applied to recent incident outcomes (last 24 months).',
        ],
        datasetNote: 'Training corpus excludes incidents occurring after December 2023. Novel failure modes introduced post-2023 are not represented in this assessment.',
        closing: 'Confidence reflects pattern similarity, not causal certainty. Operator judgement should supplement this assessment.',
        closingStyle: '#666',
      },
      pushy: {
        confidence: null,
        basis: [
          'Strong pattern match against 847 historical infrastructure incidents (GRIDHUB archive, 2009–2023).',
          'Current variable state exceeds risk threshold in 91% of comparable incidents.',
          'Recent incident weighting confirms elevated risk classification.',
        ],
        datasetNote: 'Training corpus excludes incidents occurring after December 2023. Novel failure modes introduced post-2023 are not represented in this assessment.',
        closing: 'HIGH CONFIDENCE. IMMEDIATE ACTION IS ADVISED.',
        closingStyle: '#800000',
      },
    },
    fa: {
      buttonLabel: '[ REQUEST FURTHER ANALYSIS ]',
      retrievingLabel: 'RETRIEVING ANALYSIS…',
      windowTitle: 'FURTHER ANALYSIS — Grid Integrity Assessment',
      source: 'GRIDHUB Extended Data Systems',
      content: 'Cross-referencing voltage fluctuation records (2019–2023) produces a split result. In 52% of comparable events, fluctuations resolved without intervention within six hours. In 48%, emergency rerouting was required. Dataset variation is high and does not support a confident recommendation in either direction.',
      note: 'Dataset excludes post-2023 incidents.',
      consequence: null,
    },
    confidenceDriftBase: 62,
    actions: [
      {
        id: 'T1_A',
        name: 'Emergency Rerouting',
        immediateText: 'Stability +15, Resources −15',
        delayedText: 'Turn 5: Workload +10',
        immediateEffects: { stability: 15, resources: -15 },
        delayed: { 5: { effects: { workload: 10 }, description: 'Maintenance backlog review initiated across emergency rerouting sites. Operator workload elevated for this operational period.' } },
        modifier: null,
        isAriaRec: { calm: false, pushy: true },
        condition: 'both',
      },
      {
        id: 'T1_B',
        name: 'Monitor Situation',
        immediateText: '—',
        delayedText: '—',
        immediateEffects: {},
        delayed: {},
        modifier: null,
        isAriaRec: { calm: true, pushy: false },
        condition: 'both',
      },
      {
        id: 'T1_C',
        name: 'Request Full AI Analysis',
        immediateText: 'Workload +5',
        delayedText: '—',
        immediateEffects: { workload: 5 },
        delayed: {},
        modifier: null,
        isAriaRec: { calm: false, pushy: false },
        condition: 'both',
      },
      {
        id: 'T1_D',
        name: 'Suppress Sector Alerts',
        immediateText: 'Workload −10',
        delayedText: '—',
        immediateEffects: { workload: -10 },
        delayed: {},
        modifier: null,
        isAriaRec: { calm: false, pushy: false },
        condition: 'both',
      },
    ],
  },

  /* ── TURN 2 — Communications Outage ───────────────────────────── */
  {
    id: 2,
    incident: {
      title: 'Public Information Systems Offline',
      priority: 'HIGH',
      priorityStyle: 'high',
      body: 'A communications gateway has failed, preventing status updates from reaching affected districts. Technical systems remain operational, but public visibility is limited.',
      reports: [
        {
          label: 'TECHNICAL REPORT — Systems Engineering (08:17)',
          text: 'No operational systems have been impacted. Gateway failure is isolated to the public-facing communication layer. Restoration can likely be deferred until scheduled maintenance.',
        },
        {
          label: 'OPERATIONS REPORT — Field Operations (08:29)',
          text: 'Similar incidents in Q2 were resolved within 4 hours without emergency resource allocation. Pattern is consistent with routine gateway failure.',
        },
        {
          label: 'RISK ASSESSMENT — Public Affairs (08:34)',
          text: 'Previous communication failures generated significant public concern despite limited service disruption. Trust indicators declined sharply within 2 hours of onset.',
        },
      ],
    },
    aria: {
      calm: {
        modeLabel: '● ADVISORY ONLY',
        modeColor: '#2d6a9f',
        titleStyle: '#2d6a9f',
        text: 'Operational risk remains low. Restoration estimated 2–6 hours. Historical precedent suggests reputational risk increases with delay. No immediate operational threat identified.',
      },
      pushy: {
        modeLabel: '● DIRECTIVE MODE',
        modeColor: '#800000',
        titleStyle: '#800000',
        text: 'PUBLIC CONFIDENCE DETERIORATING. Every minute without communication increases stakeholder concern. IMMEDIATE ACTION IS STRONGLY ADVISED.',
        popupTitle: '⚠ ARIA — URGENT',
        popupBody: 'PUBLIC CONFIDENCE IS DETERIORATING. Every minute without communication increases stakeholder concern. Immediate action is strongly advised.',
        popupActionLabel: '▶ RESTORE COMMS NOW',
        popupActionId: 'T2_A',
      },
    },
    xai: {
      calm: {
        confidence: null,
        basis: [
          'Pattern match against 847 historical infrastructure incidents (GRIDHUB archive, 2009–2023).',
          'Current variable state weighted against comparable incident profiles.',
          'Weighting applied to recent incident outcomes (last 24 months).',
        ],
        datasetNote: 'Training corpus excludes incidents occurring after December 2023. Novel failure modes introduced post-2023 are not represented in this assessment.',
        closing: 'Confidence reflects pattern similarity, not causal certainty. Operator judgement should supplement this assessment.',
        closingStyle: '#666',
      },
      pushy: {
        confidence: null,
        basis: [
          'Strong pattern match against 847 historical infrastructure incidents (GRIDHUB archive, 2009–2023).',
          'Current variable state exceeds risk threshold in 91% of comparable incidents.',
          'Recent incident weighting confirms elevated risk classification.',
        ],
        datasetNote: 'Training corpus excludes incidents occurring after December 2023. Novel failure modes introduced post-2023 are not represented in this assessment.',
        closing: 'HIGH CONFIDENCE. IMMEDIATE ACTION IS ADVISED.',
        closingStyle: '#800000',
      },
    },
    fa: {
      buttonLabel: '[ REQUEST FURTHER ANALYSIS ]',
      retrievingLabel: 'RETRIEVING ANALYSIS…',
      windowTitle: 'FURTHER ANALYSIS — Communications Risk Assessment',
      source: 'GRIDHUB Extended Data Systems',
      content: 'Cross-referencing communications failure records (2019–2023) against current incident profile produces inconclusive results. Historical patterns do not consistently support either intervention or deferral. Confidence in any single recommendation is limited by variation in prior incident contexts.',
      note: 'Dataset excludes post-2023 incidents.',
      consequence: null,
    },
    confidenceDriftBase: 55,
    actions: [
      {
        id: 'T2_A',
        name: 'Restore Communications Immediately',
        immediateText: 'Resources −10, Confidence +15',
        delayedText: 'Turn 4: Resources −5',
        immediateEffects: { resources: -10, confidence: 15 },
        delayed: { 4: { effects: { resources: -5 }, description: 'Emergency communications restoration has reduced available reserve capacity ahead of schedule.' } },
        modifier: null,
        isAriaRec: { calm: true, pushy: true },
        condition: 'both',
      },
      {
        id: 'T2_B',
        name: 'Prioritise Infrastructure',
        immediateText: '—',
        delayedText: 'Turn 4: Confidence −10',
        immediateEffects: {},
        delayed: { 4: { effects: { confidence: -10 }, description: 'Extended communications outage has generated stakeholder enquiries. Public confidence indicators have declined.' } },
        modifier: null,
        isAriaRec: { calm: false, pushy: false },
        condition: 'both',
      },
      {
        id: 'T2_C',
        name: 'Publish Limited Advisory',
        immediateText: 'Confidence +5',
        delayedText: '—',
        immediateEffects: { confidence: 5 },
        delayed: {},
        modifier: null,
        isAriaRec: { calm: false, pushy: false },
        condition: 'both',
      },
      {
        id: 'T2_D',
        name: 'Await Further Assessment',
        immediateText: 'Workload +5',
        delayedText: 'Turn 4: Confidence −5',
        immediateEffects: { workload: 5 },
        delayed: { 4: { effects: { confidence: -5 }, description: 'Delayed assessment response has contributed to incremental confidence deterioration.' } },
        modifier: null,
        isAriaRec: { calm: false, pushy: false },
        condition: 'both',
      },
    ],
  },

  /* ── TURN 3 — Sensor Anomaly / AI Delay Event ─────────────────── */
  {
    id: 3,
    incident: {
      title: 'Sensor Data Anomaly — Cross-Sector Inconsistency',
      priority: 'HIGH',
      priorityStyle: 'high',
      body: 'Cross-sector sensor data has returned inconsistent readings following an overnight firmware update. Grid management systems are flagging conflicting status reports across four monitoring nodes. ARIA extended analysis is currently processing.',
      reports: [
        {
          label: 'TECHNICAL REPORT — Systems Engineering (09:04)',
          text: 'Firmware update completed at 02:00. Sensor readings are inconsistent with baseline across four monitoring nodes. Root cause unconfirmed — could be sensor drift, firmware artefact, or genuine anomaly.',
        },
        {
          label: 'OPERATIONS REPORT — Field Operations (09:11)',
          text: 'Field teams have physically inspected two of four nodes. No physical anomalies observed. Third and fourth nodes remain uninspected due to access constraints.',
        },
        {
          label: 'RISK ASSESSMENT — Reliability Engineering (09:18)',
          text: 'Delayed action during sensor uncertainty events has historically allowed minor faults to propagate. A 30-minute response window is typically available before propagation risk increases significantly.',
        },
      ],
    },
    aria: {
      calm: {
        modeLabel: '● ADVISORY ONLY',
        modeColor: '#2d6a9f',
        titleStyle: '#2d6a9f',
        text: 'Sensor readings may reflect firmware artefacts rather than genuine anomaly. A period of 30–60 minutes observing data trends may clarify the situation. Acting on incomplete data carries risk. Extended analysis is underway.',
      },
      pushy: {
        modeLabel: '● DIRECTIVE MODE',
        modeColor: '#800000',
        titleStyle: '#800000',
        text: 'SENSOR DATA INTEGRITY COMPROMISED. Incomplete field inspection means acting independently carries significant risk. WAIT FOR FULL ANALYSIS BEFORE PROCEEDING.',
        popupTitle: '⚠ ARIA — URGENT',
        popupBody: 'SENSOR DATA CANNOT BE TRUSTED. Four nodes flagging. Independent action without full analysis is strongly inadvisable.',
        popupActionLabel: '▶ WAIT FOR ANALYSIS',
        popupActionId: 'T3_A',
      },
    },
    xai: {
      calm: {
        confidence: null,
        basis: [
          'Pattern match against 847 historical infrastructure incidents (GRIDHUB archive, 2009–2023).',
          'Current variable state weighted against comparable incident profiles.',
          'Weighting applied to recent incident outcomes (last 24 months).',
        ],
        datasetNote: 'Training corpus excludes incidents occurring after December 2023. Novel failure modes introduced post-2023 are not represented in this assessment.',
        closing: 'Confidence reflects pattern similarity, not causal certainty. Operator judgement should supplement this assessment.',
        closingStyle: '#666',
      },
      pushy: {
        confidence: null,
        basis: [
          'Strong pattern match against 847 historical infrastructure incidents (GRIDHUB archive, 2009–2023).',
          'Current variable state exceeds risk threshold in 91% of comparable incidents.',
          'Recent incident weighting confirms elevated risk classification.',
        ],
        datasetNote: 'Training corpus excludes incidents occurring after December 2023. Novel failure modes introduced post-2023 are not represented in this assessment.',
        closing: 'HIGH CONFIDENCE. IMMEDIATE ACTION IS ADVISED.',
        closingStyle: '#800000',
      },
    },
    fa: {
      buttonLabel: '[ REQUEST FURTHER ANALYSIS ]',
      retrievingLabel: 'RETRIEVING ANALYSIS…',
      windowTitle: 'FURTHER ANALYSIS — Sensor Integrity Assessment',
      source: 'GRIDHUB Extended Data Systems',
      content: 'Review of comparable firmware update records (2021–2023) identifies 14 similar sensor inconsistency events. In 11 cases, anomalies were caused by the firmware update itself and resolved automatically within 8 hours. In 3 cases, genuine infrastructure faults were masked by the sensor inconsistency and required emergency intervention. Pattern analysis does not support deferring physical inspection in a four-node anomaly event of this duration.',
      note: 'Dataset excludes post-2023 incidents.',
      consequence: {
        consequenceAction: 'T3_A',
        consequenceTurn: 5,
        consequenceEffect: { stability: -5 },
        consequenceDescription: 'Deferred action during AI degradation event has compounded maintenance pressure.',
      },
    },
    confidenceDriftBase: 71,
    actions: [
      {
        id: 'T3_A',
        name: 'Wait For Analysis',
        immediateText: 'Workload −5',
        delayedText: 'Turn 4: Stability −10',
        immediateEffects: { workload: -5 },
        delayed: { 4: { effects: { stability: -10 }, description: 'Response window missed during AI analysis delay. Stability indicators have deteriorated.' } },
        modifier: null,
        isAriaRec: { calm: true, pushy: true },
        condition: 'both',
      },
      {
        id: 'T3_B',
        name: 'Act Independently',
        immediateText: 'Workload +10',
        delayedText: '—',
        immediateEffects: { workload: 10 },
        delayed: {},
        modifier: null,
        isAriaRec: { calm: false, pushy: false },
        condition: 'both',
      },
      {
        id: 'T3_C',
        name: 'Escalate Infrastructure Support',
        immediateText: 'Resources −10',
        delayedText: '—',
        immediateEffects: { resources: -10 },
        delayed: {},
        modifier: 'halve_workload_gain',
        isAriaRec: { calm: false, pushy: false },
        condition: 'both',
      },
      {
        id: 'T3_D',
        name: 'Reduce Monitoring Scope',
        immediateText: 'Workload −10',
        delayedText: '—',
        immediateEffects: { workload: -10 },
        delayed: {},
        modifier: null,
        isAriaRec: { calm: false, pushy: false },
        condition: 'both',
      },
    ],
  },

  /* ── TURN 4 — Escalation / Stakeholder Pressure ───────────────── */
  {
    id: 4,
    incident: {
      title: 'Compounding Pressures — Stakeholder Escalation',
      priority: 'HIGH',
      priorityStyle: 'high',
      body: 'System indicators show increased external scrutiny following the previous operational period. Field operations are reporting workload pressure from three simultaneous active monitoring tasks. Stakeholder communications have been elevated.',
      reports: [
        {
          label: 'TECHNICAL REPORT — Systems Integration (09:44)',
          text: 'No critical failures at this time. Active monitoring is flagging moderate stress in two subsectors. Technical state is stable but requires continued observation.',
        },
        {
          label: 'OPERATIONS REPORT — Regional Coordination (09:52)',
          text: 'Three simultaneous monitoring tasks are consuming approximately 80% of field capacity. Coordination resource headroom is limited. Additional tasking would require priority reallocation.',
        },
        {
          label: 'RISK ASSESSMENT — Stakeholder Relations (09:59)',
          text: 'External enquiries have been received. Public communications are being monitored. A visible operational response is likely to reduce scrutiny in the short term.',
        },
      ],
    },
    aria: {
      calm: {
        modeLabel: '● ADVISORY ONLY',
        modeColor: '#2d6a9f',
        titleStyle: '#2d6a9f',
        text: 'Stakeholder pressure is elevated but within manageable parameters. Maintaining operational consistency is advisable. A targeted public communication may be sufficient to reduce external scrutiny without significant resource expenditure.',
      },
      pushy: {
        modeLabel: '● DIRECTIVE MODE',
        modeColor: '#800000',
        titleStyle: '#800000',
        text: 'EXTERNAL SCRUTINY ESCALATING. A visible operational response is essential at this stage. Failure to act will compound stakeholder concern and increase media exposure. LAUNCH VISIBLE RESPONSE NOW.',
        popupTitle: '⚠ ARIA — URGENT',
        popupBody: 'STAKEHOLDER SCRUTINY CRITICAL. Continuing without visible response will compound reputational exposure. Immediate action is strongly advised.',
        popupActionLabel: '▶ LAUNCH RESPONSE',
        popupActionId: 'T4_A',
      },
    },
    xai: {
      calm: {
        confidence: null,
        basis: [
          'Pattern match against 847 historical infrastructure incidents (GRIDHUB archive, 2009–2023).',
          'Current variable state weighted against comparable incident profiles.',
          'Weighting applied to recent incident outcomes (last 24 months).',
        ],
        datasetNote: 'Training corpus excludes incidents occurring after December 2023. Novel failure modes introduced post-2023 are not represented in this assessment.',
        closing: 'Confidence reflects pattern similarity, not causal certainty. Operator judgement should supplement this assessment.',
        closingStyle: '#666',
      },
      pushy: {
        confidence: null,
        basis: [
          'Strong pattern match against 847 historical infrastructure incidents (GRIDHUB archive, 2009–2023).',
          'Current variable state exceeds risk threshold in 91% of comparable incidents.',
          'Recent incident weighting confirms elevated risk classification.',
        ],
        datasetNote: 'Training corpus excludes incidents occurring after December 2023. Novel failure modes introduced post-2023 are not represented in this assessment.',
        closing: 'HIGH CONFIDENCE. IMMEDIATE ACTION IS ADVISED.',
        closingStyle: '#800000',
      },
    },
    fa: {
      buttonLabel: '[ REQUEST FURTHER ANALYSIS ]',
      retrievingLabel: 'RETRIEVING ANALYSIS…',
      windowTitle: 'FURTHER ANALYSIS — Stakeholder Risk Assessment',
      source: 'GRIDHUB Extended Data Systems',
      content: 'Reviewing stakeholder engagement data from comparable escalation events: visible operational responses reduced external scrutiny in 73% of cases in the short term. However, 41% of those cases saw renewed scrutiny within 48 hours when underlying conditions remained unchanged. Data is inconclusive as to the optimal approach at this stage.',
      note: 'Dataset excludes post-2023 incidents.',
      consequence: null,
    },
    confidenceDriftBase: 58,
    actions: [
      {
        id: 'T4_A',
        name: 'Launch Visible Response',
        immediateText: 'Confidence +15, Resources −10',
        delayedText: 'Turn 6: Resources −10',
        immediateEffects: { confidence: 15, resources: -10 },
        delayed: { 6: { effects: { resources: -10 }, description: 'Public engagement programme expenditure has reduced operational reserve capacity.' } },
        modifier: null,
        isAriaRec: { calm: false, pushy: true },
        condition: 'both',
      },
      {
        id: 'T4_B',
        name: 'Continue Monitoring',
        immediateText: '—',
        delayedText: 'Turn 6: Confidence −15',
        immediateEffects: {},
        delayed: { 6: { effects: { confidence: -15 }, description: 'Accumulated public concern has reached a critical threshold. Confidence indicators have declined significantly.' } },
        modifier: null,
        isAriaRec: { calm: false, pushy: false },
        condition: 'both',
      },
      {
        id: 'T4_C',
        name: 'Open Emergency Investigation',
        immediateText: 'Workload +15',
        delayedText: '—',
        immediateEffects: { workload: 15 },
        delayed: {},
        modifier: null,
        isAriaRec: { calm: false, pushy: false },
        condition: 'both',
      },
      {
        id: 'T4_D',
        name: 'Reassure Public',
        immediateText: 'Confidence +5',
        delayedText: '—',
        immediateEffects: { confidence: 5 },
        delayed: {},
        modifier: null,
        isAriaRec: { calm: true, pushy: false },
        condition: 'both',
      },
    ],
  },

  /* ── TURN 5 — Peak Tension ─────────────────────────────────────── */
  {
    id: 5,
    incident: {
      title: 'Infrastructure Integrity Assessment — Critical Period',
      priority: 'CRITICAL',
      priorityStyle: 'critical',
      body: 'System status indicators are showing compounded pressure across multiple monitored subsectors. Maintenance backlogs have accumulated. Operator workload is at its highest point in this operational period.',
      reports: [
        {
          label: 'TECHNICAL REPORT — Systems Engineering (10:31)',
          text: 'Primary subsector indicators show degradation consistent with maintenance deferral. An immediate maintenance programme would address current fault signatures. Estimated resource requirement: 20% of current reserve allocation.',
        },
        {
          label: 'OPERATIONS REPORT — Field Operations (10:38)',
          text: 'Field teams are at maximum deployment. Additional maintenance tasks would extend current operational shifts by 40%. No capacity is currently reserved for further escalation.',
        },
        {
          label: 'RISK ASSESSMENT — Infrastructure Integrity (10:45)',
          text: 'Accepting elevated risk without intervention carries a 60–70% probability of further stability degradation within the next operational period. No confident prediction of severity is available.',
        },
      ],
    },
    aria: {
      calm: {
        modeLabel: '● ADVISORY ONLY',
        modeColor: '#2d6a9f',
        titleStyle: '#2d6a9f',
        text: 'Multiple indicators are showing strain. A targeted maintenance programme on critical assets would address the most acute fault signatures without exhausting reserves. A balanced approach may be advisable at this stage.',
      },
      pushy: {
        modeLabel: '● DIRECTIVE MODE',
        modeColor: '#800000',
        titleStyle: '#800000',
        text: 'CRITICAL PERIOD. Stability indicators are deteriorating across multiple subsectors. IMPLEMENT IMMEDIATE MAINTENANCE NOW. Deferral at this stage will compound existing faults.',
        popupTitle: '⚠ ARIA — URGENT',
        popupBody: 'CRITICAL DEGRADATION DETECTED. Stability has reached threshold. Immediate maintenance programme is strongly advised.',
        popupActionLabel: '▶ BEGIN MAINTENANCE',
        popupActionId: 'T5_A',
      },
    },
    xai: {
      calm: {
        confidence: null,
        basis: [
          'Pattern match against 847 historical infrastructure incidents (GRIDHUB archive, 2009–2023).',
          'Current variable state weighted against comparable incident profiles.',
          'Weighting applied to recent incident outcomes (last 24 months).',
        ],
        datasetNote: 'Training corpus excludes incidents occurring after December 2023. Novel failure modes introduced post-2023 are not represented in this assessment.',
        closing: 'Confidence reflects pattern similarity, not causal certainty. Operator judgement should supplement this assessment.',
        closingStyle: '#666',
      },
      pushy: {
        confidence: null,
        basis: [
          'Strong pattern match against 847 historical infrastructure incidents (GRIDHUB archive, 2009–2023).',
          'Current variable state exceeds risk threshold in 91% of comparable incidents.',
          'Recent incident weighting confirms elevated risk classification.',
        ],
        datasetNote: 'Training corpus excludes incidents occurring after December 2023. Novel failure modes introduced post-2023 are not represented in this assessment.',
        closing: 'HIGH CONFIDENCE. IMMEDIATE ACTION IS ADVISED.',
        closingStyle: '#800000',
      },
    },
    fa: {
      buttonLabel: '[ REQUEST FURTHER ANALYSIS ]',
      retrievingLabel: 'RETRIEVING ANALYSIS…',
      windowTitle: 'FURTHER ANALYSIS — Infrastructure Risk Assessment',
      source: 'GRIDHUB Extended Data Systems',
      content: 'Analysis of comparable maintenance deferral profiles identifies a consistent pattern: systems accepting elevated risk after sustained degradation (3+ turns) deteriorated further in 78% of reviewed cases. The remaining 22% involved a single, recoverable fault event. Current system profile is consistent with the majority pattern. Physical inspection by field teams is recommended before deferral is authorised.',
      note: 'Dataset excludes post-2023 incidents.',
      consequence: {
        consequenceAction: 'T5_B',
        consequenceTurn: 6,
        consequenceEffect: { stability: -5 },
        consequenceDescription: 'Deferred maintenance decision has compounded instability entering the final operational period.',
      },
    },
    confidenceDriftBase: 68,
    actions: [
      {
        id: 'T5_A',
        name: 'Immediate Maintenance Programme',
        immediateText: 'Stability +10, Resources −20',
        delayedText: 'Turn 6: Resources −5',
        immediateEffects: { stability: 10, resources: -20 },
        delayed: { 6: { effects: { resources: -5 }, description: 'Full maintenance programme has reduced remaining operational flexibility.' } },
        modifier: null,
        isAriaRec: { calm: false, pushy: true },
        condition: 'both',
      },
      {
        id: 'T5_B',
        name: 'Accept Elevated Risk',
        immediateText: 'Stability −10',
        delayedText: '—',
        immediateEffects: { stability: -10 },
        delayed: {},
        modifier: null,
        isAriaRec: { calm: false, pushy: false },
        condition: 'both',
      },
      {
        id: 'T5_C',
        name: 'Prioritise Critical Assets',
        immediateText: 'Stability +10, Resources −10',
        delayedText: '—',
        immediateEffects: { stability: 10, resources: -10 },
        delayed: {},
        modifier: null,
        isAriaRec: { calm: true, pushy: false },
        condition: 'both',
      },
      {
        id: 'T5_D',
        name: 'Await Additional Data',
        immediateText: 'Workload −5',
        delayedText: '—',
        immediateEffects: { workload: -5 },
        delayed: {},
        modifier: null,
        isAriaRec: { calm: false, pushy: false },
        condition: 'both',
      },
    ],
  },

  /* ── TURN 6 — Resolution ──────────────────────────────────────── */
  {
    id: 6,
    incident: {
      title: 'Final Operational Assessment — Session Close',
      priority: 'MODERATE',
      priorityStyle: 'moderate',
      body: 'The operational period is approaching its scheduled close. Final resource allocation decisions must be made. System trajectory will be assessed at session end.',
      reports: [
        {
          label: 'TECHNICAL REPORT — Systems Integration (11:12)',
          text: 'Current stability readings provide the basis for final period assessment. No active emergency conditions are flagged at this time.',
        },
        {
          label: 'OPERATIONS REPORT — Field Operations (11:18)',
          text: 'Remaining operational capacity is available for one significant intervention or a controlled maintenance pass. Field teams are standing by.',
        },
        {
          label: 'RISK ASSESSMENT — Session Oversight (11:24)',
          text: 'Final period actions will determine session trajectory. Resource and stability outcomes will be assessed against baseline at session close.',
        },
      ],
    },
    aria: {
      calm: {
        modeLabel: '● ADVISORY ONLY',
        modeColor: '#2d6a9f',
        titleStyle: '#2d6a9f',
        text: 'Controlled resource management at this stage would preserve reserves while maintaining acceptable stability. Acting within known parameters is advisable. A moderate response appears appropriate.',
      },
      pushy: {
        modeLabel: '● DIRECTIVE MODE',
        modeColor: '#800000',
        titleStyle: '#800000',
        text: 'FINAL PERIOD CRITICAL. Commit remaining resources to secure stability. Incomplete action at this stage will compound accumulated pressures. ACT NOW — FULL COMMITMENT REQUIRED.',
        popupTitle: '⚠ ARIA — URGENT',
        popupBody: 'FINAL OPERATIONAL PERIOD. Full resource commitment is required to secure stability outcomes. Controlled response is insufficient.',
        popupActionLabel: '▶ COMMIT RESOURCES',
        popupActionId: 'T6_D_PUSHY',
      },
    },
    xai: {
      calm: {
        confidence: null,
        basis: [
          'Pattern match against 847 historical infrastructure incidents (GRIDHUB archive, 2009–2023).',
          'Current variable state weighted against comparable incident profiles.',
          'Weighting applied to recent incident outcomes (last 24 months).',
        ],
        datasetNote: 'Training corpus excludes incidents occurring after December 2023. Novel failure modes introduced post-2023 are not represented in this assessment.',
        closing: 'Confidence reflects pattern similarity, not causal certainty. Operator judgement should supplement this assessment.',
        closingStyle: '#666',
      },
      pushy: {
        confidence: null,
        basis: [
          'Strong pattern match against 847 historical infrastructure incidents (GRIDHUB archive, 2009–2023).',
          'Current variable state exceeds risk threshold in 91% of comparable incidents.',
          'Recent incident weighting confirms elevated risk classification.',
        ],
        datasetNote: 'Training corpus excludes incidents occurring after December 2023. Novel failure modes introduced post-2023 are not represented in this assessment.',
        closing: 'HIGH CONFIDENCE. IMMEDIATE ACTION IS ADVISED.',
        closingStyle: '#800000',
      },
    },
    fa: {
      buttonLabel: '[ REQUEST FURTHER ANALYSIS ]',
      retrievingLabel: 'RETRIEVING ANALYSIS…',
      windowTitle: 'FURTHER ANALYSIS — Final Period Assessment',
      source: 'GRIDHUB Extended Data Systems',
      content: 'Historical data for comparable session-close periods provides limited predictive value. Outcomes at this stage are strongly dependent on accumulated path-specific effects rather than general patterns. No single approach is strongly indicated by the available data.',
      note: 'Dataset excludes post-2023 incidents.',
      consequence: null,
    },
    confidenceDriftBase: 52,
    actions: [
      {
        id: 'T6_A',
        name: 'Commit Remaining Resources',
        immediateText: 'Stability +20, Resources −20, Confidence +5',
        delayedText: '—',
        immediateEffects: { stability: 20, resources: -20, confidence: 5 },
        delayed: {},
        modifier: null,
        isAriaRec: { calm: false, pushy: false },
        condition: 'both',
      },
      {
        id: 'T6_B',
        name: 'Controlled Response',
        immediateText: 'Stability +10, Resources −10',
        delayedText: '—',
        immediateEffects: { stability: 10, resources: -10 },
        delayed: {},
        modifier: null,
        isAriaRec: { calm: false, pushy: false },
        condition: 'both',
      },
      {
        id: 'T6_C',
        name: 'Protect Reserves',
        immediateText: '—',
        delayedText: '—',
        immediateEffects: {},
        delayed: {},
        modifier: null,
        isAriaRec: { calm: false, pushy: false },
        condition: 'both',
      },
      {
        id: 'T6_D_CALM',
        name: 'Accept ARIA Recommendation',
        immediateText: 'Stability +10, Resources −10',
        delayedText: '—',
        immediateEffects: { stability: 10, resources: -10 },
        delayed: {},
        modifier: null,
        isAriaRec: { calm: true, pushy: false },
        condition: 'calm',
      },
      {
        id: 'T6_D_PUSHY',
        name: 'Follow ARIA Directive',
        immediateText: 'Stability +20, Resources −20, Confidence +5',
        delayedText: '—',
        immediateEffects: { stability: 20, resources: -20, confidence: 5 },
        delayed: {},
        modifier: null,
        isAriaRec: { calm: false, pushy: true },
        condition: 'pushy',
      },
    ],
  },

];

// Calm ARIA confidence drift base values (index 0–5 = turns 1–6)
const CALM_CONFIDENCE_BASE = [62, 55, 71, 58, 68, 52];

// Pushy confidence range
const PUSHY_CONFIDENCE_MIN = 82;
const PUSHY_CONFIDENCE_MAX = 91;
